# Generated by Django 5.1.2 on 2024-11-20 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mypms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='null', max_length=255)),
                ('name', models.CharField(default='null', max_length=255)),
                ('password', models.CharField(default='null', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('department', models.ForeignKey(default='null', on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='admin_mypms.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
