# Generated by Django 5.1.2 on 2024-11-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mypms', '0003_user_delete_adminuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
