# Generated by Django 5.1.2 on 2024-11-20 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_mypms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=255)),
                ('sub_element', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('check_list', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prj_tree', to='admin_mypms.project')),
            ],
        ),
    ]
