# Generated by Django 5.1.2 on 2024-11-21 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_mypms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('checklist', models.CharField(default='Not Approved', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_element', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_element', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubElementTree',
            fields=[
                ('checklist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tree.checklist')),
                ('sub_element', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_element_tree', to='tree.subelement')),
            ],
            bases=('tree.checklist',),
        ),
        migrations.CreateModel(
            name='ElementTree',
            fields=[
                ('subelementtree_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tree.subelementtree')),
                ('main_element', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='element_tree', to='tree.element')),
            ],
            bases=('tree.subelementtree',),
        ),
        migrations.CreateModel(
            name='ProjectTree',
            fields=[
                ('elementtree_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tree.elementtree')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_tree', to='admin_mypms.project')),
            ],
            bases=('tree.elementtree',),
        ),
    ]
